# Safety parameters for CR3 robot system
safety_monitor:
  ros__parameters:
    safety:
      workspace_boundaries:
        x_min: -400.0
        x_max: 400.0
        y_min: -400.0
        y_max: 400.0
        z_min: 50.0
        z_max: 600.0
        buffer_zone: 20.0      # mm safety buffer
        
      emergency_response:
        soft_stop_decel: 200.0   # mm/s²
        hard_stop_decel: 500.0   # mm/s²
        emergency_decel: 1000.0  # mm/s²
        response_timeout: 0.1    # seconds
        
      speed_limiting:
        minimum_speed: 5.0       # mm/s minimum safe speed
        safety_speed_factor: 0.5 # Speed reduction factor in danger zones
        
      zones:
        danger_zone_distance: 10.0   # mm distance for danger zone
        warning_zone_distance: 30.0  # mm distance for warning zone
        approach_zone_distance: 50.0 # mm distance for approach zone
        
      monitoring:
        update_frequency: 100.0      # Hz monitoring frequency
