# CR3 Robot Parameters
# Core robot configuration and limits

cr3_robot:
  ros__parameters:
    # Connection settings
    tcp_ip: "192.168.5.1"
    tcp_port: 29999
    connection_timeout: 5.0
    reconnect_attempts: 3
    
    # Robot limits and capabilities
    joint_limits:
      joint_1: {min: -360.0, max: 360.0}  # degrees
      joint_2: {min: -90.0, max: 90.0}
      joint_3: {min: -150.0, max: 150.0}
      joint_4: {min: -360.0, max: 360.0}
      joint_5: {min: -90.0, max: 90.0}
      joint_6: {min: -360.0, max: 360.0}
    
    # Position limits (mm)
    position_limits:
      x: {min: -400.0, max: 400.0}
      y: {min: -400.0, max: 400.0}
      z: {min: 50.0, max: 500.0}
    
    # Velocity and acceleration limits
    max_velocity: 100.0        # mm/s
    max_acceleration: 200.0    # mm/s²
    max_jerk: 500.0           # mm/s³
    
    # Control parameters
    position_tolerance: 1.0    # mm
    velocity_tolerance: 5.0    # mm/s
    update_rate: 50.0         # Hz
