# CR3 Robot Configuration
# Default parameters for DoBot CR3 robotic arm

robot:
  # Network configuration
  ip_address: "192.168.1.6"  # Default CR3 IP address
  dashboard_port: 29999      # Dashboard service port
  move_port: 30003          # Movement service port
  feedback_port: 30004      # Real-time feedback port
  
  # Physical constraints
  workspace:
    x_min: -300.0    # mm
    x_max: 300.0     # mm
    y_min: -300.0    # mm  
    y_max: 300.0     # mm
    z_min: 0.0       # mm
    z_max: 400.0     # mm
  
  # Movement parameters
  default_speed: 0.3         # 30% of maximum speed
  max_speed: 1.0            # Maximum allowed speed
  acceleration: 0.5         # Acceleration factor
  
  # Safety settings
  emergency_stop_enabled: true
  collision_detection: true
  workspace_enforcement: true
  connection_timeout: 5.0   # seconds
  
  # Joint limits (degrees)
  joint_limits:
    j1: [-360, 360]
    j2: [-90, 90] 
    j3: [-150, 150]
    j4: [-360, 360]
    j5: [-90, 90]
    j6: [-360, 360]

# Communication settings
communication:
  tcp_enabled: true
  ros_enabled: true
  retry_attempts: 3
  retry_delay: 1.0  # seconds
  
# Logging configuration  
logging:
  level: "INFO"
  file_enabled: true
  console_enabled: true
  log_directory: "../ros2_package/log/"
